WebPizza_18/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPizza_18.Models;

namespace WebPizza_18.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        WebPizza18Entities db = new WebPizza18Entities();
        // GET: Product
        public ActionResult ListProduct()
        {
            ViewData["ProductName"] = "Tên sản phẩm";
            ViewData["CategoryName"] = "Loại";
            ViewData["Ingredients"] = "Thành phần";
            ViewData["UnitPrice"] = "Giá";
            ViewData["Size"] = "Kích cỡ";
            ViewData["GroupName"] = "Nhóm";
            List<Product> listProduct = db.Products.ToList();
            return View(listProduct);
        }
        public ActionResult LOrder()
        {
            ViewData["CustomerID"] = "Ma Khach Hang";
            ViewData["EmployeeId"] = "Ma nhan vien";
            ViewData["Create_at"] = "Thoi gian tao";
            ViewData["ShipAddress"] = "Dia chi giao hang";
            List<Order> listOrder = db.Orders.ToList();
            return View(listOrder);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Product product, FormCollection collection)
        {
            try
            {

                // TODO: Add insert logic here
                Product p = product;
                db.Products.Add(p);
                db.SaveChanges();
                return RedirectToAction("ListProduct");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            ViewData["ProductName"] = "Tên sản phẩm";
            ViewData["CategoryName"] = "Loại";
            ViewData["Ingredients"] = "Thành phần";
            ViewData["UnitPrice"] = "Giá";
            ViewData["Size"] = "Kích cỡ";
            ViewData["GroupName"] = "Nhóm";
            Product p = db.Products.FirstOrDefault(s => s.ProductID == id);
            return View(p);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(Product product, int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Product p = db.Products.First(s => s.ProductID == id);
                p.ProductName = product.ProductName;
                p.CategoryID = product.CategoryID;
                p.Ingredients = product.Ingredients;
                p.UnitPrice = product.UnitPrice;
                p.Size = product.Size;
                p.GroupID = product.GroupID;
                db.SaveChanges();
                return RedirectToAction("ListProduct");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            ViewData["ProductName"] = "Tên sản phẩm";
            ViewData["CategoryName"] = "Loại";
            ViewData["Ingredients"] = "Thành phần";
            ViewData["UnitPrice"] = "Giá";
            ViewData["Size"] = "Kích cỡ";
            ViewData["GroupName"] = "Nhóm";
            Product p = db.Products.FirstOrDefault(s => s.ProductID == id);
            return View(p);
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Product p = db.Products.First(s => s.ProductID == id);
                db.Products.Remove(p);
                db.SaveChanges();
                return RedirectToAction("ListProduct");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebPizza_18/Areas/Admin/Views/AdminHome/Create.cshtml
@model WebPizza_18.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Tao san pham</h2>


@using (Html.BeginForm("ListProduct","AdminHome", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ingredients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ingredients, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tao" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lai", "ListProduct")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebPizza_18/Areas/Admin/Views/AdminHome/Delete.cshtml
@model WebPizza_18.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Xoa san pham</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>San pham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @ViewData["ProductName"]
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @ViewData["Ingredients"]
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ingredients)
        </dd>

        <dt>
            @ViewData["UnitPrice"]
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @ViewData["Size"]
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lai", "ListProduct")
        </div>
    }
</div>

WebPizza_18/Areas/Admin/Views/AdminHome/Edit.cshtml
@model WebPizza_18.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Chinh sua</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ingredients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ingredients, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Luu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lai", "ListProduct")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebPizza_18/Areas/Admin/Views/AdminHome/LOrder.cshtml
@model IEnumerable<WebPizza_18.Models.Order>

@{
    ViewBag.Title = "LOrder";
}

<h2>Danh sach don hang</h2>

<table class="table">
    <tr>
        <th>
            @ViewData["CustomerID"]
        </th>
        <th>
            @ViewData["EmployeeID"]
        </th>
        <th>
            @ViewData["Create_at"]
        </th>
        <th>
            @ViewData["ShipAddress"]
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Create_at)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShipAddress)
        </td>
        <td>
            @Html.ActionLink("Chinh sua", "Edit", new { id=item.OrderID }) |
            @Html.ActionLink("Chi tiet", "Details", new { id=item.OrderID }) |
            @Html.ActionLink("Xoa", "Delete", new { id=item.OrderID })
        </td>
    </tr>
}

</table>

WebPizza_18/Areas/Admin/Views/AdminHome/ListProduct.cshtml
@model IEnumerable<WebPizza_18.Models.Product>

@{
    ViewBag.Title = "ListProduct";
}

<h2>Danh sách sản phẩm</h2>

<p>
    @Html.ActionLink("Tạo sản phẩm", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @ViewData["ProductName"]
        </th>
        <th>
            @ViewData["CategoryName"]
        </th>
        <th>
            @ViewData["Ingredients"]
        </th>
        <th>
            @ViewData["UnitPrice"]
        </th>
        <th>
            @ViewData["Size"]
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ingredients)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Xóa", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>